version: "3"
services:
  client:
    build:
      context: ./client
    container_name: castle-wars-client
    volumes:
      - /app/node_modules
      - ./client/:/app
    ports:
      - 3000:3000

  node:
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    build:
      context: ./server
      target: local
    container_name: castle-wars-server
    ports:
     - 8080:8080
    depends_on:
     - "mongo"
    environment:
      - MONGODB_URI=mongodb://castle-wars-mongo:27017/castle-wars

  mongo:
    image: mongo
    container_name: castle-wars-mongo
    volumes:
      - ./server/mongodb:/data/db
    ports:
      - 27017:27017
