version: "3"
services:
  client:
    build:
      context: ./client
    container_name: castle-wars-client
    volumes:
      - /app/node_modules
      - ./client/:/app
    ports:
      - 3000:3000
  web:
   build:
    context: ./server
   container_name: castle-wars-server
   ports:
     - 8000:5000
   volumes:
     - ./server:/app
